spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://ec2-23-20-211-19.compute-1.amazonaws.com:5432/d5utv53cmjmo62
    username: zdikjpgtxtfbdv
    password: 9c7a95b472a1a0e508e41b302210b5600eb68e45b4a322afbad3679f2b6782a8

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
